# Examples

## Deutsches Historisches Institut (DHI) Paris (`DE-2795`)

- [GBV-Datenbankverzeichnis](https://uri.gbv.de/database/opac-fr-751035202) (`opac-fr-751035202`)

### Neuerwerbungen / New Acquisitions / Nouvelles acquisitions

- [DHIP-Systematik / DHIP-Scheme / Classement systématique IHAP](https://vzlbs2.gbv.de/DB=44/NEUERWERBUNGEN) via [LBS](https://vzlbs2.gbv.de/DB=44/) / [IKTLIST](https://vzlbs2.gbv.de/DB=44/XML=1.0/IKTLIST)

#### Beispielanfragen

- August 2022: [dtm 202208? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202208%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- Juli 2022: [dtm 202207? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202207%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- Juni 2022: [dtm 202206? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202206%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- Mai 2022: [dtm 202205? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202205%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- April 2022: [dtm 202204? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202204%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- März 2022: [dtm 202203? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202203%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)
- Februar 2022: [dtm 202202? not \8410 a? not \8410 r? not \8600 av?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202202%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F)

**Fachgebiete August 2022**

- Deutsch-französische Beziehungen: [dtm 202208? not \8410 a? not \8410 r? not \8600 av? & \8317 Ab?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202208%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F+%26+%5C8317+Ab%3F)
- Geschichte Frankreichs (ab 1492): [dtm 202208? not \8410 a? not \8410 r? not \8600 av? & \8317 E?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202208%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F+%26+%5C8317+E%3F)
- Kulturwissenschaft: [dtm 202208? not \8410 a? not \8410 r? not \8600 av? & \8317 L?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202208%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F+%26+%5C8317+L%3F)
- Sozial- und Wirtschaftsgeschichte: [dtm 202208? not \8410 a? not \8410 r? not \8600 av? & \8317 N?](https://vzlbs2.gbv.de/DB=44/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=dtm+202208%3F+not+%5C8410+a%3F+not+%5C8410+r%3F+not+%5C8600+av%3F+%26+%5C8317+N%3F)

##### Schlüssel

- `BBG`: Bibliografische Gattung und Status (`8600`)
- `DTM`: Datum (`30`)
- `SGA`: Signatur (`8317`)
- `SLK`: Datum und Selektionsschluessel (`8410`)

##### Klassifikation (DHIP-Systematik)

- `Aa` Allgemeine Lexika und Hilfsmittel
- `Ab` Deutsch-französische Beziehungen
- `Ac` Internationale Bibliographien
- `Ad` Reihen und Serien
- `Ae` bis `Ai` Sonderdrucke und Kleinschrifttum
- `As` Festschriften
- `At` Aufsatzsammlungen einzelner Autoren
- `B` Mittelalter Deutschland und Frankreich
- `C` Deutsche Geschichte (ab 1500)
- `D` Deutsche Landesgeschichte
- `E` Geschichte Frankreichs (ab 1492)
- `F` Französische Landesgeschichte
- `G` Weltgeschichte
- `H` Geschichte einzelner Länder
- `J` Historische Hilfswissenschaften
- `K` Archive, Bibliotheken, Museen, Ausstellungen
- `L` Kulturwissenschaften
- `M` Rechts-, Verfassungs-, Verwaltungs- u. Militärgeschichte
- `N` Sozial- und Wirtschaftsgeschichte
- `P` Kirchengeschichte

##### Katalogisate

###### 1812522223 (SGA E)

- https://vzlbs2.gbv.de/DB=44/XMLPRS=N/PPN?PPN=1812522223
- https://vzlbs2.gbv.de/DB=44/XML=1.0/PPN?PPN=1812522223
- https://unapi.gbv.de/?id=opac-fr-751035202:ppn:1812522223&format=pp

```txt
101@ $a350
201@/01 $aPraesenzbestand|verfuegbar$b1$e4174727597$mmon$f44$lhttp://vzlbs2.gbv.de:8080/loan/REQ?EPN=4174727597&MTR=mon&BES=44$uPraesenzbestand$vverfuegbar
201A/01 $001-08-22
201B/01 $002-08-22$t17:43:32.000
201F/01 $00
201U/01 $0utf8
202D/01 $002-08-22$b829467$a8293/0003
203@/01 $04174727597
208@/01 $a01-08-22$bz
209A/01 $fMAG2$aEg 7085$di$x00
209C/01 $a2022/0772$x00
209G/01 $a9791024017075
220B/01 $aha geschenk Thomas Maissen
```

## Herzogin Anna Amalia Bibliothek (`DE-32`)

- [GBV-Datenbankverzeichnis](https://uri.gbv.de/database/opac-de-32) (`opac-de-32`)

### Neuerwerbungen

- [Fachgebiete](https://haab.weimar-klassik.de/newlweimar.php) via [LBS](https://opac.lbs-weimar.gbv.de/DB=2/) / [IKTLIST](https://opac.lbs-weimar.gbv.de/DB=2/XML=1.0/IKTLIST)

#### Beispielanfragen

**Allgemeines, Kultur- und Kommunikationswissenschaften, Philosophie**

- Juli 2022: [bkl 0? slk z# 2022-07?](https://opac.lbs-weimar.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=bkl+0%3F+slk+z%23+2022-07%3F)
- Juni 2022: [bkl 0? slk z# 2022-06?](https://opac.lbs-weimar.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=bkl+0%3F+slk+z%23+2022-06%3F)
- Mai 2022: [bkl 0? slk z# 2022-05?](https://opac.lbs-weimar.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=bkl+0%3F+slk+z%23+2022-05%3F)
- April 2022: [bkl 0? slk z# 2022-04?](https://opac.lbs-weimar.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=bkl+0%3F+slk+z%23+2022-04%3F)

##### Schlüssel

- `ALL`: Alle Wörter (`1016`)
- `BKL`: Basisklassifikation (`5004`)
- `SLK`: Datum und Suchschlüssel (`8410`)

##### Klassifikation (Basisklassifikation)

- `0`: Allgemeines, Kultur- und Kommunikationswissenschaften, Philosophie
- `1`: Geisteswissenschaften (ohne Philosophie)
- `2`: Kunst
- `3`: Naturwissenschaften (ohne Biowissenschaften)
- `4`: Biowissenschaften
- `5`: Technik
- `7`: Sozialwissenschaften
- `8`: Pädagogik, Volks- und Betriebswirtschaft, Recht, Verwaltung, Politik

##### Katalogisate

###### 1811465803 (BKL 1)

- https://opac.lbs-weimar.gbv.de/DB=2/XMLPRS=N/PPN?PPN=1811465803
- https://opac.lbs-weimar.gbv.de/DB=2/XML=1.0/PPN?PPN=1811465803
- https://unapi.gbv.de/?id=opac-de-32:ppn:1811465803&format=pp

```txt
101@ $a61
201@/01 $aPraesenzbestand/Lesesaalbenutzung| $b0$e4172265472$mmon$f2$uPraesenzbestand/Lesesaalbenutzung$v
201A/01 $025-07-22
201B/01 $025-07-22$t11:04:25.000
201F/01 $00
201U/01 $0utf8
202D/01 $025-07-22$b7608$a0032
203@/01 $04172265472
208@/01 $a25-07-22$bz
209A/01 $fZSAUSL$df$ic$x00
209A/01 $aZB 1621 (2022)$x09
231B/01 $a74.2022,2
237A/01 $aBitte selbst am Standort: Zeitschriftenauslage (unter Titel: "Comparativ literature") entnehmen
```

### RSS Feed

Diese Suchanfrage abonnieren (RSS)  
`vzlbs.gbv.de/php/rssopc/rss_feeds.php`

#### Parameter

- HOST
- INTPORT
- EXTPORT
- DB
- SEARCH
- SEARCHTEXT
- EDOC
- COOKIE

#### Response

```xml
<error> No search server definition or HOST, INTPORT or/and EXTPORT parameter in link.</error>
```

## Ibero-Amerikanisches Institut (`DE-204`)

- [GBV-Datenbankverzeichnis](https://uri.gbv.de/database/opac-de-204) (`opac-de-204`)

### New Acquisitions / Neuerwerbungen

- [Start](https://lbsiai.gbv.de/DB=1/NEUERWERBUNGEN) via [LBS](https://lbsiai.gbv.de/DB=1/) / [IKTLIST](https://lbsiai.gbv.de/DB=1/XML=1.0/IKTLIST)
- [New Services from the Library’s OPAC: Lists of New Acquisitions](https://web.archive.org/web/20200729065829/https://www.iai.spk-berlin.de/fileadmin/dokumentenbibliothek/Oeffentlichkeitsarbeit/Einblicke_in_die_Arbeit_des_IAI_-_Archiv/2009/032009_ENG.pdf) (2009-03)

## Niedersächsische Staats- und Universitätsbibliothek Göttingen (`DE-7`)

- [GBV-Datenbankverzeichnis](https://uri.gbv.de/database/opac-de-7) (`opac-de-7`)

### Neuerwerbungen

- Fachinformation
  - Geisteswissenschaften und Theologie
    - [Digital Humanities](https://www.sub.uni-goettingen.de/geisteswissenschaften-und-theologie/digital-humanities/neuerwerbungen/)
    - [Philosophie](https://www.sub.uni-goettingen.de/geisteswissenschaften-und-theologie/philosophie/neuerwerbungen/)
  - Naturwissenschaften, Mathematik und Informatik
    - [Informatik](https://www.sub.uni-goettingen.de/naturwissenschaften-mathematik-und-informatik/informatik/neuerwerbungen/)
  - ...

### Atom Feed

`www.sub.uni-goettingen.de/opac.atom` via [LBS](https://opac.sub.uni-goettingen.de/) / [IKTLIST](https://opac.sub.uni-goettingen.de/XML=1.0/IKTLIST)

#### Beispielanfragen

- Digital Humanities: [`q=(lkl+g+000)`](https://www.sub.uni-goettingen.de/opac.atom?q=(lkl+g+000))
- Philosophie: [q=(lkl+d+*)](https://www.sub.uni-goettingen.de/opac.atom?q=(lkl+d+*)) / [`q=(lkl d * or lkl da* or lkl db* or lkl dc* or lkl df* or lkl dh* or lkl di* or lkl dk* or lkl dm* or lkl dn* or lkl do* or lkl dq* or lkl dr* or lkl ds* or lkl dt* or lkl du*)`](https://www.sub.uni-goettingen.de/opac.atom?q=(lkl+d+*+or+lkl+da*+or+lkl+db*+or+lkl+dc*+or+lkl+df*+or+lkl+dh*+or+lkl+di*+or+lkl+dk*+or+lkl+dm*+or+lkl+dn*+or+lkl+do*+or+lkl+dq*+or+lkl+dr*+or+lkl+ds*+or+lkl+dt*+or+lkl+du*))
- Informatik: [`q=(lkl+ah*)`](https://www.sub.uni-goettingen.de/opac.atom?q=(lkl+ah*))

## Leibniz-Institut für Deutsche Sprache (IDS)

- [Neuerwerbungen](https://www.ids-mannheim.de/bibliothek/neuerwerb/) via [Koha](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=list&category=2) (Public lists)
  - [Juli 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=36) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=36)
  - [Juni 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=33) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=33)
  - [Mai 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=30) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=30)
  - [April 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=29) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=29)
  - [März 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=28) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=28)
  - [Februar 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=27) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=27)
  - [Januar 2022](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?op=view&shelfnumber=26) / [RSS](https://ids-mannheim.bsz-bw.de/cgi-bin/koha/opac-shelves.pl?rss=1&op=view&shelfnumber=26)

## Fachinformationsdienst BBI (`FID-BBI-DE-23`)

### RSS Feed

- [Katalogsuchen](https://katalog.fid-bbi.de/) via finc/VuFind
  - Beispielanfrage: [(Title:neuerwerbungsliste)](https://katalog.fid-bbi.de/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=neuerwerbungsliste&type0%5B%5D=Title)
    - [view=rss](https://katalog.fid-bbi.de/Search/Results?join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=neuerwerbungsliste&type0%5B%5D=Title&view=rss)

```xml
<rss xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" version="2.0">
<channel>
  <title>Results for (Title:neuerwerbungsliste)</title>
  <description>Showing 1 - 15 results of 15</description>
  <generator>Zend_Feed_Writer 2 (http://framework.zend.com)</generator>
  <link>https://katalog.fid-bbi.de/Search/Results?sort=score+desc&limit=50&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=neuerwerbungsliste&type0%5B%5D=Title</link>
  <opensearch:totalResults>15</opensearch:totalResults>
  <opensearch:startIndex>0</opensearch:startIndex>
  <opensearch:itemsPerPage>50</opensearch:itemsPerPage>
  <opensearch:Query role="request" searchTerms="neuerwerbungsliste" startIndex="0"/>
  ...
  <item>
    <title><i>Neuerwerbungsliste / Nordstadtbücherei, Stadtbüchereien Hannover</i>. [Hannover].</title>
    <link>https://katalog.fid-bbi.de/Record/183-629835926</link>
    <guid>https://katalog.fid-bbi.de/Record/183-629835926</guid>
    <slash:comments>0</slash:comments>
  </item>
  <item>
    <title><i>Neuerwerbungsliste / Stadtbüchereien Hannover, Fahrbücherei</i>. [Hannover].</title>
    <link>https://katalog.fid-bbi.de/Record/183-629835896</link>
    <guid>https://katalog.fid-bbi.de/Record/183-629835896</guid>
    <slash:comments>0</slash:comments>
  </item>
  ...
</channel>
</rss>
```

## Stanford University

### Science Library

- [New acquisitions](https://library.stanford.edu/science/collections/new-acquisitions) via [SearchWork](https://searchworks.stanford.edu/) (VuFind)
  - [2021 archives](https://library.stanford.edu/science/collections/new-acquisitions/2021-archives)

### SearchWorks

- [System Status](https://library-status.stanford.edu/)

## Heidelberg University

- [MyUB-Info verwenden](https://www.ub.uni-heidelberg.de/service/MyUBinfo/verwenden.html#profil-anlegen-mit-7-klicks)
- [Neuerwerbungslisten](https://www.ub.uni-heidelberg.de/helios/nel/NEL.html)
  - [Neuerwerbungslisten der UB](https://www.ub.uni-heidelberg.de/helios/nel/Welcome.html)
  - [Neuerwerbungslisten der Fachinformationsdienste arthistoricum.net, Propylaeum und CrossAsia](https://www.ub.uni-heidelberg.de/helios/nel_ssg/)
    - [Ägyptologie](https://www.ub.uni-heidelberg.de/helios/nel_ssg/00/AY00/Welcome.html)
    - [Klassische Archäologie](https://www.ub.uni-heidelberg.de/helios/nel_ssg/00/AC00/Welcome.html)
    - [Mittlere und Neuere Kunstgeschichte bis 1945 und Allgemeine Kunstwissenschaft](https://www.ub.uni-heidelberg.de/helios/nel_ssg/Kunst.html)
    - [Südasien](https://www.ub.uni-heidelberg.de/helios/nel_ssg/Suedasien.html)
  - [Dezentrale Bibliotheken](https://www.ub.uni-heidelberg.de/helios/nel_inst/Welcome.html)

## Kunsthochschule für Medien Köln (`DE-Kn185`)

### Neuerwerbungen / New Acquisitions

- [Monatslisten](https://www.khm.de/bib_neuerwerbungen/) / [monthly list](https://en.khm.de/bib_neuerwerbungen/) via Primo / OPAC

#### Beispielanfragen

- Januar 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0122
- Februar 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0222
- März 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0322
- April 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0422
- Mai 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0522
- Juni 2022: http://bibkatalog.khm.de/F/?func=find-a&find_code=ABR&request=kn185:0622

### SDI via OPAC

[Hilfe](http://bibkatalog.khm.de/)

> SDI (Selective Dissemination of Information) ist ein Dienst, über den Benutzer über neue Titel in ihrem Interessengebiet informiert werden können. Mit dem SDI-Mechanismus sendet Ihre Bibliothek eine Nachricht, sobald es neue Bücher in einem bestimmten Themenfeld oder neue Hefte einer Zeitschrift gibt.
>
> Sie müssen eine SDI-Berechtigung in Ihrem Profil haben, um SDI-Anfragen anlegen zu können.
>
> Um eine SDI-Anfrage anzulegen, klicken Sie aus der Ergebnisliste oder dem Suchverlauf auf einen SDI-Link. So gelangen Sie auf die Seite SDI-Profil (neu/ändern). In diesem Fenster können Sie ein neues SDI-Profil anlegen oder ein bestehendes ändern. Es enthält die folgenden Felder:
>
> - SDI-Name: Geben Sie den Namen an, unter dem Ihre Anfrage gespeichert werden soll.
> - Print Format: Wählen Sie das Format, in dem Sie die Titel erhalten möchten.
> - Intervall: Legen Sie die Abstände zwischen den Durchläufen der SDI-Anfrage fest, z.B. sieben Tage oder vier Wochen.
> - SDI-Nachricht: Geben Sie Text ein, der in der gesendeten E-Mail erscheinen soll.
> - SDI-Anfrage: Hier wird der ursprüngliche Suchbegriff angezeigt (z.B. words=Buddhism).
> - SDI-Zweigstelle: Sie können die Anfrage für eine einzelne Zweigstelle oder für alle Zweigstellen laufen lassen.
> - SDI-Datenbankliste: Wählen Sie die Datenbanken, in denen Ihre Anfrage laufen soll.
> - Alternative E-Mail: Sie können Ihre SDI-Ergebnisse an eine weitere E-Mail-Adresse senden lassen.
> - E-Mail-Betreff: Wählen Sie einen Betreff für die SDI-Ergebnislisten.
> - Ablaufdatum: Wählen Sie ein Ablaufdatum. Die Ergebnislisten werden nach diesem Datum nicht mehr gesendet.
> - SDI aussetzen von/bis: Sie können für bestimmte Zeiträume (z.B. Ferien) die SDI-Suchen aussetzen. Bis zum Ende dieses Zeitraums werden Sie keine Benachrichtigungen erhalten.
> - Codierung: Wählen Sie den Zeichensatz, in dem Sie die Listen empfangen wollen.
> - Nachricht bei keinen Ergebnissen: Hier stellen Sie ein, ob Sie auch eine Benachrichtigung erhalten möchten, wenn die Suche keine Ergebnisse hat.
>
> Um alle Ihre SDI-Profile zu sehen, gehen Sie in den Benutzerausweis und klicken Sie dort auf den Link SDI-Profile. Dort können Sie Ihre Profile ändern, duplizieren oder löschen. Wenn Sie auf Sofort suchen klicken, wird die Suche sogleich ausgeführt; eine E-Mail-Benachrichtigung wird in diesem Fall nicht verschickt.

### Siehe auch

[Top 10 Ausleihe](https://www.khm.de/bib_top_ausleihe/) (Quartals- und Jahresausleihe)

## Leo Baeck Institute (LBI)

- [New Library Acquisitions](https://www.lbi.org/collections/new-library-acquisitions/) / [Neuerwerbungen der LBI Bibliothek](https://www.lbi.org/de/collections/new-library-acquisitions/) via Primo
  - [View new library acquisitions in the Catalog](http://search.cjh.org/primo-explore/search?query=any,contains,%22LBI%20Library%20New%20Acquisitions%202022%22&tab=default_tab&search_scope=LBI&vid=lbi&lang=en_US&offset=0)
    - „Liste von Neuerwerbungen in unserem online Katalog“
  - [View 2021 library acquisitions in the Catalog](http://search.cjh.org/primo-explore/search?query=any,contains,%22LBI%20Library%20New%20Acquisitions%202021%22&tab=default_tab&search_scope=LBI&vid=lbi&lang=en_US&offset=0)
    - „Bibliothekserwerbungen 2021 im Katalog anzeigen“

## University of Florence

- [Nuove acquisizioni](https://sbafirenze.it/Alma_newacq2/) via ALMA

## University of Oregon

- [New Acquisitions List](https://library.uoregon.edu/new-acquisitions-list) via Primo

## Warburg Library

- [New Acquisitions](https://warburg.libguides.com/collections/new) via [LibGuides](http://warburg.libguides.com/)
- [#NewAcquisitions](https://twitter.com/search?q=(%23NewAcquisitions)%20(from%3AWarburg_Library)&f=live) via [Twitter](https://twitter.com/Warburg_Library) (\@Warburg_Library)
