# Publications

## SLUB Dresden

### Landesbibliothek (1920–1990)

- Verzeichnis der ... im Lesesaal ausgestellten Neuerwerbungen (1924–1927)
  - DNB: [#](#)
  - ZDB: [2558267-7](https://ld.zdb-services.de/resource/2558267-7)
  - KXP: [629378223](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=629378223&INDEXSET=21)
  - SLUB: [0-629378223](https://katalog.slub-dresden.de/id/0-629378223)
- Die ... im Lesesaal ausgestellten Neuerwerbungen (1927–1932)
  - DNB: [019244797](https://d-nb.info/019244797)
  - ZDB: [2558248-3](https://ld.zdb-services.de/resource/2558248-3)
  - KXP: [629378096](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=629378096&INDEXSET=21)
  - SLUB: [0-629378096](https://katalog.slub-dresden.de/id/0-629378096)
- Verzeichnis ... vom ...–... ausgestellte Neuerwerbungen (1933–1945)
  - DNB: [019244797](https://d-nb.info/019244797)
  - ZDB: [2558270-7](https://ld.zdb-services.de/resource/2558270-7)
  - KXP: [629378258](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=629378258&INDEXSET=21)
  - SLUB: [0-629378258](https://katalog.slub-dresden.de/id/0-629378258)
- Neuerwerbungen (1952–1962)
  - DNB: [018298907](https://d-nb.info/018298907)
  - ZDB: [1327433-8](https://ld.zdb-services.de/resource/1327433-8)
  - KXP: [214085732](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=214085732&INDEXSET=21)
  - SLUB: [#](#)
- Neuerwerbungen und Nachrichten (1962–1986)
  - DNB: [010697152](https://d-nb.info/010697152)
  - ZDB: [123998-3](https://ld.zdb-services.de/resource/123998-3)
  - ISSN: [0233-1098](https://portal.issn.org/resource/ISSN-L/0233-1098)
  - KXP: [166186317](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=166186317&INDEXSET=21)
  - SLUB: [0-166186317](https://katalog.slub-dresden.de/id/0-166186317)
- Neuerwerbungen (1987–1992)
  - DNB: [010932232](https://d-nb.info/010932232)
  - ZDB: [154573-5](https://ld.zdb-services.de/resource/154573-5)
  - ISSN [0863-1263](https://portal.issn.org/resource/ISSN-L/0863-1263)
  - KXP: [166389714](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=166389714&INDEXSET=21)
  - SLUB: [0-166389714](https://katalog.slub-dresden.de/id/0-166389714)

#### Musik (1960–1980)

- Neuerwerbungen / Musikabteilung (1961–1974)
  - DNB: [010793976](https://d-nb.info/010793976)
  - ZDB: [136187-9](https://ld.zdb-services.de/resource/136187-9)
  - ISSN: [0419-7321](https://portal.issn.org/resource/ISSN-L/0419-7321)
  - KXP: [16625505X](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=16625505X&INDEXSET=21)
  - SLUB: [0-16625505X](https://katalog.slub-dresden.de/id/0-16625505X)
  - Digitalisat: [urn:nbn:de:bsz:14-db-id3116633463](http://nbn-resolving.de/urn:nbn:de:bsz:14-db-id3116633463)
- Bibliographie Musik (1975–1988)
  - DNB: [010768327](https://d-nb.info/010768327)
  - ZDB: [132979-0](https://ld.zdb-services.de/resource/132979-0)
  - ISSN: [0232-7678](https://portal.issn.org/resource/ISSN-L/0232-7678)
  - KXP: [129326798](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=129326798&INDEXSET=21)
  - SLUB: [0-129326798](https://katalog.slub-dresden.de/id/0-129326798)
  - Digitalisat: [urn:nbn:de:bsz:14-db-id3116640913](http://nbn-resolving.de/urn:nbn:de:bsz:14-db-id3116640913)

#### Stenografie (1950–2000)

- Neuerwerbungen ... (Auswahl) der Bibliothek des Stenographischen Landesamtes, Dresden (1954–1955)
  - DNB: [013070126](https://d-nb.info/013070126)
  - ZDB: [555076-2](https://ld.zdb-services.de/resource/555076-2)
  - KXP: [167640704](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167640704&INDEXSET=21)
  - SLUB: [0-167640704](https://katalog.slub-dresden.de/id/0-167640704)
- Zugangsliste ... der Bibliothek des Stenographischen Landesamtes, Dresden (1956–1957)
  - DNB: [#](#)
  - ZDB: [2715193-1](https://ld.zdb-services.de/resource/2715193-1)
  - KXP: [746064233](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=746064233&INDEXSET=21)
  - SLUB: [0-746064233](https://katalog.slub-dresden.de/id/0-746064233)
- Neuerwerbungen (Auswahl) der Bibliothek des Stenographischen Landesamtes Dresden (1958–1965)
  - DNB: [013070118](https://d-nb.info/013070118)
  - ZDB: [555075-0](https://ld.zdb-services.de/resource/555075-0)
  - KXP: [167640690](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167640690&INDEXSET=21)
  - SLUB: [0-167640690](https://katalog.slub-dresden.de/id/0-167640690)
- Neuerwerbungen / Abteilung Stenographische Bibliothek (1966–1989)
  - DNB: [01307010X](https://d-nb.info/01307010X)
  - ZDB: [555074-9](https://ld.zdb-services.de/resource/555074-9)
  - ISSN: [0863-0461](https://portal.issn.org/resource/ISSN-L/0863-0461)
  - KXP: [167640682](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167640682&INDEXSET=21)
  - SLUB: [0-167640682](https://katalog.slub-dresden.de/id/0-167640682)
- Neuerwerbungen in Auswahl / Stenografische Sammlung (1989–1995)
  - DNB: [#](#)
  - ZDB: [1174289-6](https://ld.zdb-services.de/resource/1174289-6)
  - ISSN: [0863-0461](https://portal.issn.org/resource/ISSN-L/0863-0461)
  - KXP: [171291468](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171291468&INDEXSET=21)
  - SLUB: [0-171291468](https://katalog.slub-dresden.de/id/0-171291468)
- Neuerwerbungen in Auswahl / Stenografische Sammlung (1996–2001)
  - DNB: [#](#)
  - ZDB: [1357342-1](https://ld.zdb-services.de/resource/1357342-1)
  - ISSN: [0863-0461](https://portal.issn.org/resource/ISSN-L/0863-0461)
  - KXP: [223268119](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=223268119&INDEXSET=21)
  - SLUB: [0-223268119](https://katalog.slub-dresden.de/id/0-223268119)

### Universitätsbibliothek (1930–1980)

- Neuerwerbungen der Bibliothek der Technischen Hochschule Dresden (1931–1944 / 1951–1952)
  - DNB: [01513640X](https://d-nb.info/01513640X)
  - ZDB: [972562-3](https://ld.zdb-services.de/resource/972562-3)
  - KXP: [169345742](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=169345742&INDEXSET=21)
  - SLUB: [0-169345742](https://katalog.slub-dresden.de/id/0-169345742)
    - [0-1430193816](https://katalog.slub-dresden.de/id/0-1430193816)
- Auswahlliste der Neuerwerbungen (1952–1961)
  - DNB: [011481730](https://d-nb.info/011481730)
  - ZDB: [244625-X](https://ld.zdb-services.de/resource/244625-X)
  - KXP: [16666880X](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=16666880X&INDEXSET=21)
  - SLUB: [0-16666880X](https://katalog.slub-dresden.de/id/0-16666880X)
- Neuerwerbungen der Bibliothek der Technischen Universität Dresden (1961–1966)
  - DNB: [013003763](https://d-nb.info/013003763)
  - ZDB: [548044-9](https://ld.zdb-services.de/resource/548044-9)
  - KXP: [167587005](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167587005&INDEXSET=21)
  - SLUB: [0-167587005](https://katalog.slub-dresden.de/id/0-167587005)
- Neuerwerbungen technischer Hochschulbibliotheken der DDR (1967–1972)
  - DNB: [011287381](https://d-nb.info/011287381)
  - ZDB: [218730-9](https://ld.zdb-services.de/resource/218730-9)
  - ISSN: [0045-1916](https://portal.issn.org/resource/ISSN-L/0045-1916)
  - KXP: [166543586](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=166543586&INDEXSET=21)
  - SLUB: [0-166543586](https://katalog.slub-dresden.de/id/0-166543586)
- Neuerwerbungsverzeichnis (1974–1985)
  - Reihe 1: Gesellschaftswissenschaften, Wirtschaftswissenschaften (1974–1985)
    - DNB: [013000349](https://d-nb.info/013000349)
    - ZDB: [547688-4](https://ld.zdb-services.de/resource/547688-4)
    - ISSN: [0323-3200](https://portal.issn.org/resource/ISSN-L/0323-3200)
    - KXP: [167584189](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584189&INDEXSET=21)
    - SLUB: [0-167584189](https://katalog.slub-dresden.de/id/0-167584189)
  - Reihe 2: Mathematik, mathematische Kybernetik und Rechentechnik (1974–1985)
    - DNB: [013000365](https://d-nb.info/013000365)
    - ZDB: [547690-2](https://ld.zdb-services.de/resource/547690-2)
    - ISSN: [0233-1691](https://portal.issn.org/resource/ISSN-L/0233-1691)
    - KXP: [167584200](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584200&INDEXSET=21)
    - SLUB: [0-167584200](https://katalog.slub-dresden.de/id/0-167584200)
  - Reihe 3: Physik (1974–1985)
    - DNB: [013000381](https://d-nb.info/013000381)
    - ZDB: [547692-6](https://ld.zdb-services.de/resource/547692-6)
    - ISSN: [0233-1748](https://portal.issn.org/resource/ISSN-L/0233-1748)
    - KXP: [167584227](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584227&INDEXSET=21)
    - SLUB: [0-167584227](https://katalog.slub-dresden.de/id/0-167584227)
  - Reihe 4: Chemie, chemische Technologie und chemische Produktion, Verfahrenstechnik (1974–1985)
    - DNB: [013000403](https://d-nb.info/013000403)
    - ZDB: [547694-X](https://ld.zdb-services.de/resource/547694-X)
    - ISSN: [0233-1799](https://portal.issn.org/resource/ISSN-L/0233-1799)
    - KXP: [167584243](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584243&INDEXSET=21)
    - SLUB: [0-167584243](https://katalog.slub-dresden.de/id/0-167584243)
  - Reihe 5: Geo- und Astrowissenschaften, Biologie, Umweltschutz (1975–1985)
    - DNB: [01300039X](https://d-nb.info/01300039X)
    - ZDB: [547693-8](https://ld.zdb-services.de/resource/547693-8)
    - ISSN: [0233-1845](https://portal.issn.org/resource/ISSN-L/0233-1845)
    - KXP: [167584235](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584235&INDEXSET=21)
    - SLUB: [0-167584235](https://katalog.slub-dresden.de/id/0-167584235)
  - Reihe 6: Technik insgesamt, allgemeine und ingenieurtheoretische Disziplinen (1975–1985)
    - DNB: [013000438](https://d-nb.info/013000438)
    - ZDB: [547697-5](https://ld.zdb-services.de/resource/547697-5)
    - ISSN: [0233-1896](https://portal.issn.org/resource/ISSN-L/0233-1896)
    - KXP: [167584278](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584278&INDEXSET=21)
    - SLUB: [0-167584278](https://katalog.slub-dresden.de/id/0-167584278)
  - Reihe 7: Elektrotechnik, Energetik (1975–1979)
    - DNB: [013000446](https://d-nb.info/013000446)
    - ZDB: [547698-7](https://ld.zdb-services.de/resource/547698-7)
    - ISSN: [0233-1993](https://portal.issn.org/resource/ISSN-L/0233-1993)
    - KXP: [167584286](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584286&INDEXSET=21)
    - SLUB: [0-167584286](https://katalog.slub-dresden.de/id/0-167584286)
  - Reihe 8: Informationstechnik, Informationsverarbeitung, Regelungs- und Steuerungstechnik (1976–1979)
    - DNB: [013000454](https://d-nb.info/013000454)
    - ZDB: [547699-9](https://ld.zdb-services.de/resource/547699-9)
    - ISSN: [0233-2043](https://portal.issn.org/resource/ISSN-L/0233-2043)
    - KXP: [167584294](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584294&INDEXSET=21)
    - SLUB: [0-167584294](https://katalog.slub-dresden.de/id/0-167584294)
  - Reihe 7/8: Energetik, Elektrotechnik, Informationstechnik, Regelungs- und Steuerungstechnik, feinmechanischer und optischer Gerätebau (1980–1985)
    - DNB: [013660128](https://d-nb.info/013660128)
    - ZDB: [631241-X](https://ld.zdb-services.de/resource/631241-X)
    - ISSN: [0233-1942](https://portal.issn.org/resource/ISSN-L/0233-1942)
    - KXP: [168077817](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=168077817&INDEXSET=21)
    - SLUB: [0-168077817](https://katalog.slub-dresden.de/id/0-168077817)
  - Reihe 9: Fertigungstechnik, Maschinenbau (1978–1985)
    - DNB: [013660136](https://d-nb.info/013660136)
    - ZDB: [631242-1](https://ld.zdb-services.de/resource/631242-1)
    - ISSN: [0233-2094](https://portal.issn.org/resource/ISSN-L/0233-2094)
    - KXP: [168077825](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=168077825&INDEXSET=21)
    - SLUB: [0-168077825](https://katalog.slub-dresden.de/id/0-168077825)
  - Reihe 10: Bauwesen, Wasserwesen, Verkehrswesen (1975–1985)
    - DNB: [013000462](https://d-nb.info/013000462)
    - ZDB: [547700-1](https://ld.zdb-services.de/resource/547700-1)
    - ISSN: [0233-2140](https://portal.issn.org/resource/ISSN-L/0233-2140)
    - KXP: [167584308](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=167584308&INDEXSET=21)
    - SLUB: [0-167584308](https://katalog.slub-dresden.de/id/0-167584308)
  - Reihe 11: Forstwirtschaft, Landwirtschaft, Jagd (1978–1985)
    - DNB: [016696573](https://d-nb.info/016696573)
    - ZDB: [1140854-6](https://ld.zdb-services.de/resource/1140854-6)
    - ISSN: [0233-2191](https://portal.issn.org/resource/ISSN-L/0233-2191)
    - KXP: [171020502](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171020502&INDEXSET=21)
    - SLUB: [0-171020502](https://katalog.slub-dresden.de/id/0-171020502)
- Neuerwerbungen (1986–1989)
  - DNB: [017159938](https://d-nb.info/017159938)
  - ZDB: [1188669-9](https://ld.zdb-services.de/resource/1188669-9)
  - ISSN: [0863-0291](https://portal.issn.org/resource/ISSN-L/0863-0291)
  - KXP: [182231720](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=182231720&INDEXSET=21)
  - SLUB: [0-182231720](https://katalog.slub-dresden.de/id/0-182231720)

#### Tharandt (1920–1990)

- Neuerwerbungen / Bücherei d. Forstlichen Hochschule Tharandt (1922–1932)
  - DNB: [#](#)
  - ZDB: [1140838-8](https://ld.zdb-services.de/resource/1140838-8)
  - KXP: [171020367](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171020367&INDEXSET=21)
  - SLUB: [0-171020367](https://katalog.slub-dresden.de/id/0-171020367)
- Zugänge / Bücherei der Forstlichen Hochschule Tharandt (1937–1959)
  - DNB: [01204623X](https://d-nb.info/01204623X)
  - ZDB: [350514-5](https://ld.zdb-services.de/resource/350514-5)
  - KXP: [166938521](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=166938521&INDEXSET=21)
  - SLUB: [0-166938521](https://katalog.slub-dresden.de/id/0-166938521)
- Zugänge / Technische Hochschule Dresden, Bücherei der Fakultät für Forstwirtschaft Tharandt (1959–1961)
  - DNB: [012046248](https://d-nb.info/012046248)
  - ZDB: [350515-7](https://ld.zdb-services.de/resource/350515-7)
  - KXP: [16693853X](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=16693853X&INDEXSET=21)
  - SLUB: [0-16693853X](https://katalog.slub-dresden.de/id/0-16693853X)
- Zugänge / Technische Universität Dresden, Bücherei der Fakultät für Forstwirtschaft Tharandt (1961–1962)
  - DNB: [012046256](https://d-nb.info/012046256)
  - ZDB: [350516-9](https://ld.zdb-services.de/resource/350516-9)
  - KXP: [166938548](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=166938548&INDEXSET=21)
  - SLUB: [0-166938548](https://katalog.slub-dresden.de/id/0-166938548)
- Zugänge / Technische Universität Dresden, Bibliothek d. Fakultät für Forstwirtschaft Tharandt (1962–1968)
  - DNB: [#](#)
  - ZDB: [1140848-0](https://ld.zdb-services.de/resource/1140848-0)
  - KXP: [171020456](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171020456&INDEXSET=21)
  - SLUB: [0-171020456](https://katalog.slub-dresden.de/id/0-171020456)
- Zugänge / Technische Universität Dresden, Bibliothek d. Sektion Forstwirtschaft Tharandt (1969–1976)
  - DNB: [#](#)
  - ZDB: [1140851-0](https://ld.zdb-services.de/resource/1140851-0)
  - KXP: [171020480](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171020480&INDEXSET=21)
  - SLUB: [0-171020480](https://katalog.slub-dresden.de/id/0-171020480)
- [vgl. oben Neuerwerbungsverzeichnis. Reihe 11 (1978–1985)]
- Neuerwerbungen Forstwissenschaft (1986–1992)
  - DNB: [01669659X](https://d-nb.info/01669659X)
  - ZDB: [1140856-X](https://ld.zdb-services.de/resource/1140856-X)
  - ISSN: [1439-507X](https://portal.issn.org/resource/ISSN-L/1439-507X)
  - SLUB: [0-171020529](https://katalog.slub-dresden.de/id/0-171020529)

#### Importliteratur (1970)

- Originalsprachige Importliteratur aus der Sowjetunion: Neuerwerbungen (1972–1978)
  - DNB: [017062519](https://d-nb.info/017062519)
  - ZDB: [1178598-6](https://ld.zdb-services.de/resource/1178598-6)
  - KXP: [17133387X](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=17133387X&INDEXSET=21)
  - SLUB: [0-17133387X](https://katalog.slub-dresden.de/id/0-17133387X)

#### Mikroelektronik (1970–1980)

- Mikroelektronik: Zusammenstellung der Neuerwerbungen (1978–1982)
  - DNB: [209556722](https://d-nb.info/209556722)
    - [209556730](https://d-nb.info/209556730)
    - [209556749](https://d-nb.info/209556749)
  - KXP: [1155958071](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=1155958071&INDEXSET=21)
    - [1155958160](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=1155958160&INDEXSET=21)
    - [1155958241](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=1155958241&INDEXSET=21)
  - SLUB: [0-1155958071](https://katalog.slub-dresden.de/id/0-1155958071)
    - [0-1155958160](https://katalog.slub-dresden.de/id/0-1155958160)
    - [0-1155958241](https://katalog.slub-dresden.de/id/0-1155958241)

### Bibliothek der Pädagogischen Hochschule (1980–1990)

- Neuerwerbungen der Hochschulbibliothek (1983–1990)
  - ZDB: [1161414-6](https://ld.zdb-services.de/resource/1161414-6)
  - DNB: [551512296](https://d-nb.info/551512296)
  - KXP: [171176464](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171176464&INDEXSET=21)
  - SLUB: [0-171176464](https://katalog.slub-dresden.de/id/0-171176464)

### Bibliothek der Hochschule für Verkehrswesen (1950–1990)

- Neuerwerbungen (1950–1962)
  - DNB: [016903579](https://d-nb.info/016903579)
  - ZDB: [1162197-7](https://ld.zdb-services.de/resource/1162197-7)
  - KXP: [171182308](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171182308&INDEXSET=21)
  - SLUB: [0-171182308](https://katalog.slub-dresden.de/id/0-171182308)
- Neuerwerbungen (1962–1965)
  - DNB: [016903587](https://d-nb.info/016903587)
  - ZDB: [1162198-9](https://ld.zdb-services.de/resource/1162198-9)
  - KXP: [171182316](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=171182316&INDEXSET=21)
  - SLUB: [0-171182316](https://katalog.slub-dresden.de/id/0-171182316)
- Neuerwerbsverzeichnis von Literatur über das Transport- und Nachrichtenwesen (1976–1978)
  - DNB: [#](#)
  - ZDB: [2756027-2](https://ld.zdb-services.de/resource/2756027-2)
  - KXP: [778374556](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=778374556&INDEXSET=21)
  - SLUB: [0-778374556](https://katalog.slub-dresden.de/id/0-778374556)
- Neuerwerbungen von Literatur über das Transport- und Nachrichtenwesen (1979–1991)
  - DNB: [99788651X](https://d-nb.info/99788651X)
  - ZDB: [2523483-3](https://ld.zdb-services.de/resource/2523483-3)
  - KXP: [612289885](https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=612289885&INDEXSET=21)
  - SLUB: [0-612289885](https://katalog.slub-dresden.de/id/0-612289885)

## SUB Hamburg

- Neuerwerbungen ausländischer Literatur (1949–1950)
  - SLUB: [0-169119793](https://katalog.slub-dresden.de/id/0-169119793)
- Neuerwerbungen (1950–1972)
  - SLUB: [0-167632299](https://katalog.slub-dresden.de/id/0-167632299)

## American Institute of Electrical Engineers

### Proceedings (1905–1919)

- [IEEE Xplore](https://ieeexplore.ieee.org/servlet/opac?punumber=6530810)
- ZDB: [2735330-8](https://ld.zdb-services.de/resource/2735330-8)
- EZB: [2735330-8](https://ezb.ur.de/?2735330-8)
  - XML: [201677](https://ezb.ur.de/ezeit/detail.phtml?jour_id=201677&xmloutput=1)
- LOC: [lccn.loc.gov/2014202414](https://lccn.loc.gov/2014202414) / [www.loc.gov/item/2014202414](https://www.loc.gov/item/2014202414/)

#### Library Accessions

- [queryText=library accessions&searchWithin="Publication Number":6530810](https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=library%20accessions&searchWithin=%22Publication%20Number%22:6530810) (IEEE Xplore)
- Vol. 29, No. 9, September 1910 (DOI: [10.1109/PAIEE.1910.6659928](https://doi.org/10.1109/PAIEE.1910.6659928))
